image: docker:latest

stages:
  - test
  - deploy

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u=$CI_REGISTRY_USER -p="$CI_REGISTRY_PASSWORD" $CI_REGISTRY

test:
  stage: test
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME ./
    - docker run --name jupiter-gravity $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME npm run test;

deploy_branch:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME ./
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  except:
    - master

deploy_master:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest ./
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master