sudo: required
services:
  - docker
language: node_js
os: ubuntu
node_js:
  - "9"
before_install:
  - npm i -g npm@latest
install:
  - if [$TRAVIS_BRANCH  == 'master'];
    then docker build -t sigwo/gravity:latest ./;
    else docker build -t sigwo/gravity:$TRAVIS_BRANCH ./;
    fi
script:
  - if [$TRAVIS_BRANCH  == 'master'];
    then docker run --name gravity sigwo/gravity:latest npm run test;
    else docker run --name gravity sigwo/gravity:$TRAVIS_BRANCH npm run test;
    fi
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [$TRAVIS_BRANCH  == 'master'];
    then docker push sigwo/gravity:latest;
    else docker push sigwo/gravity:$TRAVIS_BRANCH;
    fi